export const protectedRoutes = [
  "/login",
  "/dashboard/customer",
  "/dashboard/customer/select-meals",
  "/dashboard/customer/track-order",
  "/dashboard/customer/manage-preferences",
  "/dashboard/provider",
  "/dashboard/provider/manage-menus",
  "/dashboard/provider/view-orders",
  "/dashboard/provider/responses",
  "/find-meals",
  "/cart",
  "/post-meal-menu",
  "/responses",
];
